version: "3"
services:
  postgres:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 100
    build:
      context: ./pgml-extension/
      dockerfile: Dockerfile.local
    ports:
      - "5433:5432"
    command:
      - sleep
      - infinity
  dashboard:
    depends_on:
       postgres:
         condition: service_healthy
    build:
      context: ./pgml-dashboard/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/pgml_development
    command: bash -c "sqlx migrate run && cargo run"
