version: "3"
services:
  postgres:
    healthcheck:
      test: psql -c 'SELECT 1' -U postgres -h 127.0.0.1
      interval: 2s
      retries: 3
      start_period: 30s
      timeout: 2s
    build:
      context: ./pgml-extension/
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    command:
      - sleep
      - infinity
  dashboard:
    healthcheck:
      test: curl http://localhost:8000
      interval: 15s
      retries: 3
      timeout: 2s
    restart: on-failure
    depends_on:
      - postgres
    build:
      context: ./pgml-dashboard/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command:
      - python3
      - manage.py
      - runserver
      - 0.0.0.0:8000
  docs:
    build:
      context: ./pgml-docs/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command:
      - mkdocs
      - serve
      - -a 0.0.0.0:8001
