[package]
name = "cargo-pgml-components"
version = "0.1.25"
edition = "2021"
authors = ["PostgresML <team@postgresml.org>"]
license = "MIT"
description = "A tool for bundling SCSS and JavaScript Stimulus components like Rails does."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3"
convert_case = "0.6"
clap = { version = "4", features = ["derive"] }
md5 = "0.7"
log = "0.4"
env_logger = "0.10"
anyhow = "1"
owo-colors = "3"
sailfish = "0.8"
regex = "1"
toml = "0.7"
serde = { version = "1", features = ["derive"] }
file-lock = "2"
serde_json = "1"
notify = "6"
notify-debouncer-full = "0.3"
once_cell = "1"

[dev-dependencies]
assert_cmd = "2"
assert_fs = "1"
predicates = "3"
