name: tests
on:
  push:
  workflow_dispatch:
jobs:
  tests:
    runs-on: buildjet-4vcpu-ubuntu-2204
    defaults:
      run:
        working-directory: pgml-extension
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update && \
            DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt-get install -y \
              curl \
              build-essential \
              libopenblas-dev \
              clang \
              python3-dev \
              libpython3-dev \
              postgresql \
              postgresql-server-dev-14 \
              pkg-config \
              python3-pip \
              python3 \
              mold
          sudo pip3 install -r requirements.txt
      - name: Cache dependencies
        uses: buildjet/cache@v3
        with:
          path: |
            ~/.cargo
            pgml-extension/target
            ~/.pgrx
          key: ${{ runner.os }}-rust-2-${{ hashFiles('pgml-extension/Cargo.lock') }}
      - name: Submodules
        run: |
          git submodule update --init --recursive
      - name: Run tests
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source ~/.cargo/env
          cargo install cargo-pgrx --version "0.9.8" --locked

          if [[ ! -d ~/.pgrx ]]; then
            cargo pgrx init
          fi

          cargo pgrx test

#          cargo pgrx start
#          psql -p 28815 -h 127.0.0.1 -d pgml -P pager -f tests/test.sql
#          cargo pgrx stop
