name: Deploy to beta

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      name:
        description: "Just a trigger"
        required: false
        default: "Hello"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install ssh key
        run: mkdir -p ~/.ssh && echo "${{ secrets.BETA_SSH_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Start deploy
        run: ssh -o "StrictHostKeyChecking=no" root@${{ secrets.BETA_IP }} '(cd /root; bash infrastructure/ubuntu/ubuntu_20_04_lts.sh) >&- 2>&- <&- &'

